# Generated by Django 5.0.1 on 2024-01-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='img',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='pictures'),
        ),
    ]
