# Generated by Django 5.0.1 on 2024-01-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_place_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('address', models.TextField()),
                ('img', models.ImageField(default='path/to/default/image.jpg', upload_to='pictures')),
            ],
        ),
    ]
