# Generated by Django 5.0.1 on 2024-01-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_destinations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
